[package]
name = "htmlsnob_lsp"
version = { workspace = true }
edition = { workspace = true }

[dependencies]
htmlsnob = { path = "../htmlsnob" }
htmlsnob_rules = { path = "../htmlsnob_rules" }
tokio = { version = "1.43.0", features = ["full"] }
tower-lsp = "0.20.0"

