[package]
name = "htmlsnob_test_data_fetcher"
version = { workspace = true }
edition = { workspace = true }

[dependencies]
tokio = { version = "1.43.0", features = ["full"] }
serde = { version = "1.0.219", features = ["derive"] }
reqwest = "0.12.12"
serde_json = "1.0.140"
dotenvy = "0.15.7"
