# -------------------------------------------------------------------------------------------------------------------------------------------------------------
# -------------------- rules: CONTENT -------------------------------------------------------------------------------------------------------------------------
# -------------------------------------------------------------------------------------------------------------------------------------------------------------
#        # Enforces that an element does not have text content.
#        [[rules]]
#        kind = "text_disallowed"
#        severity = "error"
#        tags = ["SELF_CLOSING", "html", "head", "colgroup", "table", "thead", "tbody"]
