[package]
name = "htmlsnob_cli"
version = { workspace = true }
edition = { workspace = true }

[dependencies]
clap = { version = "4.5.35", features = ["derive"] }
glob = "0.3.2"
htmlsnob = { path = "../htmlsnob" }
htmlsnob_rules = { path = "../htmlsnob_rules" }
